### ISSUE TITLE
Transport(Invalid URL: No port number in URL (default port is not supported))

### ISSUE THREAD

**Issue by xlc** [chevdor/subwasm#36]
```
$ subwasm diff wss://karura-rpc-2.aca-api.network/ws karura-2001.wasm
Running subwasm v0.16.1
  🅰️  Chain(OnchainBlock { endpoint: WebSocket("wss://karura-rpc-2.aca-api.network/ws"), block_ref: None })
Transport(Invalid URL: No port number in URL (default port is not supported))
thread 'main' panicked at 'Can only diff if the 2 runtimes can load: Loading("OnchainBlock { endpoint: WebSocket(\"wss://karura-rpc-2.aca-api.network/ws\"), block_ref: None }")', lib/src/lib.rs:113:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I need to make it `subwasm diff wss://karura-rpc-2.aca-api.network:443/ws karura-2001.wasm` to work

Why default port is not supported?

**Comment by chevdor** [comment]
This error is coming from [jsonrpsee](https://github.com/paritytech/jsonrpsee/blob/68154226650808d795d018989ea269c60c47c96d/ws-client/src/transport.rs#L361-L363).

There is an easy fix for you for now since `karura` or even `kar` are known and I did provide the ports, but you need to swap the arguments in the current implementation:
```
subwasm diff karura-2001.wasm -b karura
```

I am not happy with this `--chain-a|-a` / `--chain-b|-b` so I that will be improved in the future.

**Comment by Neopallium** [comment]
@chevdor FYI, the `subwasm diff` demo video in the readme has this same error and doesn't show runtime differences.

**Comment by chevdor** [comment]
All the issues mentioned here are now fixed with the new version.
You can check with:
```
subwasm get --chain karura
subwasm diff wss://karura-rpc-2.aca-api.network/ws runtime_000.wasm
```

You should get an output similar to:
```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
No change detected
SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: false

!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
